name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  id-token: write
  attestations: write
  contents: write

jobs:
  release:
    uses: bazel-contrib/.github/.github/workflows/release_ruleset.yaml@v7.2.2
    with:
      release_files: |
        sign-here-v*.tar.gz
        sign-here-v*-darwin-arm64
      prerelease: false

  publish-to-bcr:
    needs: release
    permissions:
      contents: write
      id-token: write
      attestations: write
    uses: bazel-contrib/publish-to-bcr/.github/workflows/publish.yaml@v0.2.2
    with:
      tag_name: ${{ github.ref_name }}
      registry_fork: "maxwellelliott/bazel-central-registry"
      draft: true
    secrets:
      publish_token: ${{ secrets.BCR_PUBLISH_TOKEN }}
